### ISSUE TITLE
How do I blacklist something?

### ISSUE THREAD

**Issue by Splinterverse** [BloodDragon2580/FastOpen#1]
When I type /fastopen, I don't see how to add an item to the blacklist. 

I want to add conduits for the Shadowlands covenants. They require being near the Forge of Bonds so having them appear in the middle of the screen when I can't actually pop them is not ideal. If you want to update the addon to take that into account, that works to, but otherwise I'm looking for advice on how I can add them. An example is Discipline of the Grove (which is appearing onscreen for me as I type this). 

Love the addon though! Thanks!

**Comment by BloodDragon2580** [comment]
I won't be home until Monday then I'll get in touch. I'm on a business trip.

**Comment by Splinterverse** [comment]
That's fine. I understand. I also would like to know what keys or buttons I press to move the addon to a different spot on screen. I don't see that in the menu. Also, for my original question, another good example is the Large Crate of Salvage from Warlords of Draenor. You can't pop that open unless you are in your garrison's Salvage Yard.

**Comment by BloodDragon2580** [comment]
Is possible permanently blacklist item (remove from button) by CTRL right-click, this permanent blacklist can be cleared via slash command "/fastopen clear" or from Game Menu, Interface, AddOns.
Is possible remove permanently blacklisted item just one with /fastopen unlist itemID. ItemID come from query via /fastopen list.
